"Resource/UI/winpanel.res"
{
	"TFStatsSummary"
	{
		"ControlName"				"EditablePanel"
		"fieldName"					"TFStatsSummary"
		"xpos"						"0"
		"ypos"						"0"
		"wide"						"f0"
		"tall"						"480"
		"visible"					"0"
		"enabled"					"1"
		"bgcolor_override"			"Blank"
	}
	
	"Background"
	{
		"ControlName"						"ImagePanel"
		"fieldName"							"Background"
		"xpos"								"0"
		"ypos"								"-20"
		"zpos"								"0"
		"wide"								"f0"
		"tall"								"480"
		"visible"							"1"
		"enabled"							"1"
		"image"								"replay/thumbnails/menu/menugif"
		"scaleimage"						"1"
	}
	
	"Background2"
	{
		"ControlName"						"EditablePanel"
		"fieldName"							"Background2"
		"xpos"								"0"
		"ypos"								"0"
		"zpos"								"0"
		"wide"								"f0"
		"tall"								"f0"
		"visible"							"1"
		"enabled"							"1"
		"bgcolor_override"					"0 0 0 150"
		"paintbackground"					"1"
		"paintborder"						"0"
		"PaintBackgroundType"				"0"		
	}
	
	"StatData"
	{
		"ControlName"				"EditablePanel"
		"fieldName"					"StatData"
		"xpos"						"0"
		"ypos"						"45"
		"zpos"						"1"
		"wide"						"f0"
		"tall"						"480"
		"visible"					"1"
		"enabled"					"1"

		"InteractiveHeaders"	
		{
			"ControlName"			"EditablePanel"
			"fieldName"				"InteractiveHeaders"
			"xpos"					"0"
			"ypos"					"0"
			"zpos"					"2"
			"wide"					"f0"
			"tall"					"480"
			"visible"				"1"
			"enabled"				"1"
			
			"BarChartComboABG"
			{
				"ControlName"		"ImagePanel"
				"fieldName"			"BarChartComboABG"
				"xpos"				"c-199"
				"ypos"				"10"
				"zpos"				"2"
				"wide"				"159"
				"tall"				"20"
				"autoResize"		"0"
				"pinCorner"			"0"
				"visible"			"1"
				"enabled"			"1"
				"tabPosition"		"0"
				"paintbackground"	"0"
				"paintborder"		"1"
				"border"			"Black"
			}

			"BarChartComboA"
			{
				"ControlName"		"ComboBox"
				"fieldName"			"BarChartComboA"
				"Font"				"HudFontSmallestBold"
				"xpos"				"c-195"
				"ypos"				"14"
				"zpos"				"3"
				"wide"				"151"
				"tall"				"12"
				"autoResize"		"0"
				"pinCorner"			"0"
				"visible"			"1"
				"enabled"			"1"
				"tabPosition"		"1"
				"textHidden"		"0"
				"editable"			"0"
				"maxchars"			"-1"
				"NumericInputOnly"	"0"
				"unicode"			"0"
				
				"fgcolor_override"					"TanLight"
				"bgcolor_override"					"Blank"
				"disabledFgColor_override" 			"TanLight"
				"disabledBgColor_override" 			"Blank"
				"selectionColor_override" 			"Blank"
				"selectionTextColor_override" 		"TanLight"
				"defaultSelectionBG2Color_override"	"Blank"
				
				"Button"
				{
					"defaultFgColor_override"		"TanLight"
					"defaultBgColor_override"		"Blank"
					"armedFgColor_override"			"TanLight"
					"armedBgColor_override"			"Blank"
					"paintbackgroundtype"			"2"
				}
			}
			
			"BarChartComboBBG"
			{
				"ControlName"		"ImagePanel"
				"fieldName"			"BarChartComboBBG"
				"xpos"				"c40"
				"ypos"				"10"
				"zpos"				"2"
				"wide"				"159"
				"tall"				"20"
				"autoResize"		"0"
				"pinCorner"			"0"
				"visible"			"1"
				"enabled"			"1"
				"tabPosition"		"0"
				"paintbackground"	"0"
				"paintborder"		"1"
				"border"			"Black"
			}
			
			"BarChartComboB"
			{
				"ControlName"		"ComboBox"
				"fieldName"			"BarChartComboB"
				"Font"				"HudFontSmallestBold"
				"xpos"				"c44"
				"ypos"				"14"
				"zpos"				"3"
				"wide"				"151"
				"tall"				"12"
				"autoResize"		"0"
				"pinCorner"			"0"
				"visible"			"1"
				"enabled"			"1"
				"tabPosition"		"1"
				"textHidden"		"0"
				"editable"			"0"
				"maxchars"			"-1"
				"NumericInputOnly"	"0"
				"unicode"			"0"
				
				"fgcolor_override"					"TanLight"
				"bgcolor_override"					"Blank"
				"disabledFgColor_override" 			"TanLight"
				"disabledBgColor_override" 			"Blank"
				"selectionColor_override" 			"Blank"
				"selectionTextColor_override" 		"TanLight"
				"defaultSelectionBG2Color_override"	"Blank"
				
				"Button"
				{
					"defaultFgColor_override"		"TanLight"
					"defaultBgColor_override"		"Blank"
					"armedFgColor_override"			"TanLight"
					"armedBgColor_override"			"Blank"
					"paintbackgroundtype"			"2"
				}
			}
			
			"ClassComboBG"
			{
				"ControlName"		"ImagePanel"
				"fieldName"			"ClassComboBG"
				"xpos"				"c-40"
				"ypos"				"10"
				"zpos"				"2"
				"wide"				"80"
				"tall"				"20"
				"autoResize"		"0"
				"pinCorner"			"0"
				"visible"			"1"
				"enabled"			"1"
				"tabPosition"		"0"
				"paintbackground"	"0"
				"paintborder"		"1"
				"border"			"Black"
			}
			
			"ClassCombo"
			{
				"ControlName"		"ComboBox"
				"fieldName"			"ClassCombo"
				"xpos"				"c-36"
				"ypos"				"14"
				"zpos"				"10"
				"wide"				"72"
				"tall"				"12"
				"autoResize"		"0"
				"pinCorner"			"0"
				"visible"			"1"
				"enabled"			"1"
				"tabPosition"		"1"
				"textHidden"		"0"
				"editable"			"0"
				"maxchars"			"-1"
				"NumericInputOnly"	"0"
				"unicode"			"0"
				
				"fgcolor_override"					"TanLight"
				"bgcolor_override"					"Blank"
				"disabledFgColor_override" 			"TanLight"
				"disabledBgColor_override" 			"Blank"
				"selectionColor_override" 			"Blank"
				"selectionTextColor_override" 		"TanLight"
				"defaultSelectionBG2Color_override"	"Blank"
				
				"Button"
				{
					"defaultFgColor_override"		"TanLight"
					"defaultBgColor_override"		"Blank"
					"armedFgColor_override"			"TanLight"
					"armedBgColor_override"			"Blank"
					"paintbackgroundtype"			"2"
				}
			}
		}
		
		"AveragesBG"
		{
			"ControlName"			"EditablePanel"
			"fieldName"				"AveragesBG"
			"xpos"					"9999"
		}
		"AveragesLabel"
		{
			"ControlName"			"Label"
			"fieldName"				"AveragesLabel"
			"xpos"					"9999"
		}
		
		///////////////////////////////////////////////////
		///////////////////////BAR 1///////////////////////
		///////////////////////////////////////////////////
		
		"ClassLabel1"
		{
			"ControlName"			"Label"
			"fieldName"				"ClassLabel1"
			"font"					"TF2Secondary16"
			"labelText"				"%class1%"
			"textAlignment"			"center"
			"xpos"					"c-40"
			"ypos"					"30"
			"zpos"					"5"
			"wide"					"80"
			"tall"					"20"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"AllCaps"				"1"
			"border"				"Black"
		}
		"ClassBarBG1A"
		{
			"ControlName"			"ImagePanel"
			"fieldName"				"ClassBarBG1A"
			"xpos"					"c-199"
			"ypos"					"30"
			"zpos"					"2"
			"wide"					"159"
			"tall"					"20"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"tabPosition"			"0"
			"paintbackground"		"0"
			"paintborder"			"1"
			"border"				"Black"
		}
		"ClassBar1A"
		{
			"ControlName"			"ImagePanel"
			"fieldName"				"ClassBar1A"
			"xpos"					"c-195"
			"ypos"					"34"
			"zpos"					"3"
			"wide"					"151"
			"tall"					"12"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"tabPosition"			"0"	
			"fillcolor"				"Gray"
			"PaintBackgroundType"	"0"
			"alpha"					"50"
		}
		"ClassBarLabel1A"
		{
			"ControlName"			"Label"
			"fieldName"				"ClassBarLabel1A"
			"font"					"TF2Secondary16"
			"labelText"				"%classbarlabel1A%"
			"textAlignment"			"west"
			"xpos"					"c-195"
			"ypos"					"30"
			"zpos"					"6"
			"wide"					"100"
			"tall"					"20"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
		}
		"ClassBarBG1B"
		{
			"ControlName"			"ImagePanel"
			"fieldName"				"ClassBarBG1B"
			"xpos"					"c40"
			"ypos"					"30"
			"zpos"					"2"
			"wide"					"159"
			"tall"					"20"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"tabPosition"			"0"
			"paintbackground"		"0"
			"paintborder"			"1"
			"border"				"Black"
		}
		"ClassBar1B"
		{
			"ControlName"			"ImagePanel"
			"fieldName"				"ClassBar1B"
			"xpos"					"c44"
			"ypos"					"34"
			"zpos"					"3"
			"wide"					"151"
			"tall"					"12"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"tabPosition"			"0"	
			"fillcolor"				"Gray"
			"PaintBackgroundType"	"0"
			"alpha"					"50"
		}
		"ClassBarLabel1B"
		{
			"ControlName"			"Label"
			"fieldName"				"ClassBarLabel1B"
			"font"					"TF2Secondary16"
			"labelText"				"%classbarlabel1B%"
			"textAlignment"			"west"
			"xpos"					"c44"
			"ypos"					"30"
			"zpos"					"6"
			"wide"					"100"
			"tall"					"20"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
		}
		
		///////////////////////////////////////////////////
		///////////////////////BAR 2///////////////////////
		///////////////////////////////////////////////////
		
		"ClassLabel2"
		{
			"ControlName"			"Label"
			"fieldName"				"ClassLabel2"
			"font"					"TF2Secondary16"
			"labelText"				"%class2%"
			"textAlignment"			"center"
			"xpos"					"c-40"
			"ypos"					"50"
			"zpos"					"5"
			"wide"					"80"
			"tall"					"20"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"AllCaps"				"1"
			"border"				"Black"
		}
		
		"ClassBarBG2A"
		{
			"ControlName"			"ImagePanel"
			"fieldName"				"ClassBarBG2A"
			"xpos"					"c-199"
			"ypos"					"50"
			"zpos"					"2"
			"wide"					"159"
			"tall"					"20"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"tabPosition"			"0"
			"paintbackground"		"0"
			"paintborder"			"1"
			"border"				"Black"
		}
		"ClassBar2A"
		{
			"ControlName"			"ImagePanel"
			"fieldName"				"ClassBar2A"
			"xpos"					"c-195"
			"ypos"					"54"
			"zpos"					"3"
			"wide"					"151"
			"tall"					"12"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"tabPosition"			"0"	
			"fillcolor"				"Gray"
			"PaintBackgroundType"	"0"
			"alpha"					"50"
		}
		"ClassBarLabel2A"
		{
			"ControlName"			"Label"
			"fieldName"				"ClassBarLabel2A"
			"font"					"TF2Secondary16"
			"labelText"				"%classbarlabel2A%"
			"textAlignment"			"west"
			"xpos"					"c-195"
			"ypos"					"50"
			"zpos"					"6"
			"wide"					"100"
			"tall"					"20"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
		}
		
		"ClassBarBG2B"
		{
			"ControlName"			"ImagePanel"
			"fieldName"				"ClassBarBG2B"
			"xpos"					"c40"
			"ypos"					"50"
			"zpos"					"2"
			"wide"					"159"
			"tall"					"20"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"tabPosition"			"0"
			"paintbackground"		"0"
			"paintborder"			"1"
			"border"				"Black"
		}
		"ClassBar2B"
		{
			"ControlName"			"ImagePanel"
			"fieldName"				"ClassBar2B"
			"xpos"					"c44"
			"ypos"					"54"
			"zpos"					"3"
			"wide"					"151"
			"tall"					"12"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"tabPosition"			"0"	
			"fillcolor"				"Gray"
			"PaintBackgroundType"	"0"
			"alpha"					"50"
		}
		"ClassBarLabel2B"
		{
			"ControlName"			"Label"
			"fieldName"				"ClassBarLabel2B"
			"font"					"TF2Secondary16"
			"labelText"				"%classbarlabel2B%"
			"textAlignment"			"west"
			"xpos"					"c44"
			"ypos"					"50"
			"zpos"					"6"
			"wide"					"100"
			"tall"					"20"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
		}
		
		///////////////////////////////////////////////////
		///////////////////////BAR 3///////////////////////
		///////////////////////////////////////////////////
		
		"ClassLabel3"
		{
			"ControlName"			"Label"
			"fieldName"				"ClassLabel3"
			"font"					"TF2Secondary16"
			"labelText"				"%class3%"
			"textAlignment"			"center"
			"xpos"					"c-40"
			"ypos"					"70"
			"zpos"					"5"
			"wide"					"80"
			"tall"					"20"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"AllCaps"				"1"
			"border"				"Black"
		}
		
		"ClassBarBG3A"
		{
			"ControlName"			"ImagePanel"
			"fieldName"				"ClassBarBG3A"
			"xpos"					"c-199"
			"ypos"					"70"
			"zpos"					"2"
			"wide"					"159"
			"tall"					"20"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"tabPosition"			"0"
			"paintbackground"		"0"
			"paintborder"			"1"
			"border"				"Black"
		}
		"ClassBar3A"
		{
			"ControlName"			"ImagePanel"
			"fieldName"				"ClassBar3A"
			"xpos"					"c-195"
			"ypos"					"74"
			"zpos"					"3"
			"wide"					"151"
			"tall"					"12"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"tabPosition"			"0"	
			"fillcolor"				"Gray"
			"PaintBackgroundType"	"0"
			"alpha"					"50"
		}
		"ClassBarLabel3A"
		{
			"ControlName"			"Label"
			"fieldName"				"ClassBarLabel3A"
			"font"					"TF2Secondary16"
			"labelText"				"%classbarlabel3A%"
			"textAlignment"			"west"
			"xpos"					"c-195"
			"ypos"					"70"
			"zpos"					"6"
			"wide"					"100"
			"tall"					"20"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
		}
		
		"ClassBarBG3B"
		{
			"ControlName"			"ImagePanel"
			"fieldName"				"ClassBarBG3B"
			"xpos"					"c40"
			"ypos"					"70"
			"zpos"					"2"
			"wide"					"159"
			"tall"					"20"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"tabPosition"			"0"
			"paintbackground"		"0"
			"paintborder"			"1"
			"border"				"Black"
		}
		"ClassBar3B"
		{
			"ControlName"			"ImagePanel"
			"fieldName"				"ClassBar3B"
			"xpos"					"c44"
			"ypos"					"74"
			"zpos"					"3"
			"wide"					"151"
			"tall"					"12"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"tabPosition"			"0"	
			"fillcolor"				"Gray"
			"PaintBackgroundType"	"0"
			"alpha"					"50"
		}
		"ClassBarLabel3B"
		{
			"ControlName"			"Label"
			"fieldName"				"ClassBarLabel3B"
			"font"					"TF2Secondary16"
			"labelText"				"%classbarlabel3B%"
			"textAlignment"			"west"
			"xpos"					"c44"
			"ypos"					"70"
			"zpos"					"6"
			"wide"					"100"
			"tall"					"20"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
		}
		
		///////////////////////////////////////////////////
		///////////////////////BAR 4///////////////////////
		///////////////////////////////////////////////////
		
		"ClassLabel4"
		{
			"ControlName"			"Label"
			"fieldName"				"ClassLabel4"
			"font"					"TF2Secondary16"
			"labelText"				"%class4%"
			"textAlignment"			"center"
			"xpos"					"c-40"
			"ypos"					"90"
			"zpos"					"5"
			"wide"					"80"
			"tall"					"20"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"AllCaps"				"1"
			"border"				"Black"
		}
		
		"ClassBarBG4A"
		{
			"ControlName"			"ImagePanel"
			"fieldName"				"ClassBarBG4A"
			"xpos"					"c-199"
			"ypos"					"90"
			"zpos"					"2"
			"wide"					"159"
			"tall"					"20"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"tabPosition"			"0"
			"paintbackground"		"0"
			"paintborder"			"1"
			"border"				"Black"
		}
		"ClassBar4A"
		{
			"ControlName"			"ImagePanel"
			"fieldName"				"ClassBar4A"
			"xpos"					"c-195"
			"ypos"					"94"
			"zpos"					"3"
			"wide"					"151"
			"tall"					"12"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"tabPosition"			"0"	
			"fillcolor"				"Gray"
			"PaintBackgroundType"	"0"
			"alpha"					"50"
		}
		"ClassBarLabel4A"
		{
			"ControlName"			"Label"
			"fieldName"				"ClassBarLabel4A"
			"font"					"TF2Secondary16"
			"labelText"				"%classbarlabel4A%"
			"textAlignment"			"west"
			"xpos"					"c-195"
			"ypos"					"90"
			"zpos"					"6"
			"wide"					"100"
			"tall"					"20"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
		}
		
		"ClassBarBG4B"
		{
			"ControlName"			"ImagePanel"
			"fieldName"				"ClassBarBG4B"
			"xpos"					"c40"
			"ypos"					"90"
			"zpos"					"2"
			"wide"					"159"
			"tall"					"20"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"tabPosition"			"0"
			"paintbackground"		"0"
			"paintborder"			"1"
			"border"				"Black"
		}
		"ClassBar4B"
		{
			"ControlName"			"ImagePanel"
			"fieldName"				"ClassBar4B"
			"xpos"					"c44"
			"ypos"					"94"
			"zpos"					"3"
			"wide"					"151"
			"tall"					"12"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"tabPosition"			"0"	
			"fillcolor"				"Gray"
			"PaintBackgroundType"	"0"
			"alpha"					"50"
		}
		"ClassBarLabel4B"
		{
			"ControlName"			"Label"
			"fieldName"				"ClassBarLabel4B"
			"font"					"TF2Secondary16"
			"labelText"				"%classbarlabel4B%"
			"textAlignment"			"west"
			"xpos"					"c44"
			"ypos"					"90"
			"zpos"					"6"
			"wide"					"100"
			"tall"					"20"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
		}
		
		///////////////////////////////////////////////////
		///////////////////////BAR 5///////////////////////
		///////////////////////////////////////////////////
		
		"ClassLabel5"
		{
			"ControlName"			"Label"
			"fieldName"				"ClassLabel5"
			"font"					"TF2Secondary16"
			"labelText"				"%class5%"
			"textAlignment"			"center"
			"xpos"					"c-40"
			"ypos"					"110"
			"zpos"					"5"
			"wide"					"80"
			"tall"					"20"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"AllCaps"				"1"
			"border"				"Black"
		}
		
		"ClassBarBG5A"
		{
			"ControlName"			"ImagePanel"
			"fieldName"				"ClassBarBG5A"
			"xpos"					"c-199"
			"ypos"					"110"
			"zpos"					"2"
			"wide"					"159"
			"tall"					"20"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"tabPosition"			"0"
			"paintbackground"		"0"
			"paintborder"			"1"
			"border"				"Black"
		}
		"ClassBar5A"
		{
			"ControlName"			"ImagePanel"
			"fieldName"				"ClassBar5A"
			"xpos"					"c-195"
			"ypos"					"114"
			"zpos"					"3"
			"wide"					"151"
			"tall"					"12"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"tabPosition"			"0"	
			"fillcolor"				"Gray"
			"PaintBackgroundType"	"0"
			"alpha"					"50"
		}
		"ClassBarLabel5A"
		{
			"ControlName"			"Label"
			"fieldName"				"ClassBarLabel5A"
			"font"					"TF2Secondary16"
			"labelText"				"%classbarlabel5A%"
			"textAlignment"			"west"
			"xpos"					"c-195"
			"ypos"					"110"
			"zpos"					"6"
			"wide"					"100"
			"tall"					"20"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
		}
		
		"ClassBarBG5B"
		{
			"ControlName"			"ImagePanel"
			"fieldName"				"ClassBarBG5B"
			"xpos"					"c40"
			"ypos"					"110"
			"zpos"					"2"
			"wide"					"159"
			"tall"					"20"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"tabPosition"			"0"
			"paintbackground"		"0"
			"paintborder"			"1"
			"border"				"Black"
		}
		"ClassBar5B"
		{
			"ControlName"			"ImagePanel"
			"fieldName"				"ClassBar5B"
			"xpos"					"c44"
			"ypos"					"114"
			"zpos"					"3"
			"wide"					"151"
			"tall"					"12"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"tabPosition"			"0"	
			"fillcolor"				"Gray"
			"PaintBackgroundType"	"0"
			"alpha"					"50"
		}
		"ClassBarLabel5B"
		{
			"ControlName"			"Label"
			"fieldName"				"ClassBarLabel5B"
			"font"					"TF2Secondary16"
			"labelText"				"%classbarlabel5B%"
			"textAlignment"			"west"
			"xpos"					"c44"
			"ypos"					"110"
			"zpos"					"6"
			"wide"					"100"
			"tall"					"20"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
		}
		
		///////////////////////////////////////////////////
		///////////////////////BAR 6///////////////////////
		///////////////////////////////////////////////////
		
		"ClassLabel6"
		{
			"ControlName"			"Label"
			"fieldName"				"ClassLabel6"
			"font"					"TF2Secondary16"
			"labelText"				"%class6%"
			"textAlignment"			"center"
			"xpos"					"c-40"
			"ypos"					"130"
			"zpos"					"5"
			"wide"					"80"
			"tall"					"20"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"AllCaps"				"1"
			"border"				"Black"
		}
		
		"ClassBarBG6A"
		{
			"ControlName"			"ImagePanel"
			"fieldName"				"ClassBarBG6A"
			"xpos"					"c-199"
			"ypos"					"130"
			"zpos"					"2"
			"wide"					"159"
			"tall"					"20"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"tabPosition"			"0"
			"paintbackground"		"0"
			"paintborder"			"1"
			"border"				"Black"
		}
		"ClassBar6A"
		{
			"ControlName"			"ImagePanel"
			"fieldName"				"ClassBar6A"
			"xpos"					"c-195"
			"ypos"					"134"
			"zpos"					"3"
			"wide"					"151"
			"tall"					"12"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"tabPosition"			"0"	
			"fillcolor"				"Gray"
			"PaintBackgroundType"	"0"
			"alpha"					"50"
		}
		"ClassBarLabel6A"
		{
			"ControlName"			"Label"
			"fieldName"				"ClassBarLabel6A"
			"font"					"TF2Secondary16"
			"labelText"				"%classbarlabel6A%"
			"textAlignment"			"west"
			"xpos"					"c-195"
			"ypos"					"130"
			"zpos"					"6"
			"wide"					"100"
			"tall"					"20"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
		}
		
		"ClassBarBG6B"
		{
			"ControlName"			"ImagePanel"
			"fieldName"				"ClassBarBG6B"
			"xpos"					"c40"
			"ypos"					"130"
			"zpos"					"2"
			"wide"					"159"
			"tall"					"20"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"tabPosition"			"0"
			"paintbackground"		"0"
			"paintborder"			"1"
			"border"				"Black"
		}
		"ClassBar6B"
		{
			"ControlName"			"ImagePanel"
			"fieldName"				"ClassBar6B"
			"xpos"					"c44"
			"ypos"					"134"
			"zpos"					"3"
			"wide"					"151"
			"tall"					"12"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"tabPosition"			"0"	
			"fillcolor"				"Gray"
			"PaintBackgroundType"	"0"
			"alpha"					"50"
		}
		"ClassBarLabel6B"
		{
			"ControlName"			"Label"
			"fieldName"				"ClassBarLabel6B"
			"font"					"TF2Secondary16"
			"labelText"				"%classbarlabel6B%"
			"textAlignment"			"west"
			"xpos"					"c44"
			"ypos"					"130"
			"zpos"					"6"
			"wide"					"100"
			"tall"					"20"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
		}
		
		///////////////////////////////////////////////////
		///////////////////////BAR 7///////////////////////
		///////////////////////////////////////////////////
		
		"ClassLabel7"
		{
			"ControlName"			"Label"
			"fieldName"				"ClassLabel7"
			"font"					"TF2Secondary16"
			"labelText"				"%class7%"
			"textAlignment"			"center"
			"xpos"					"c-40"
			"ypos"					"150"
			"zpos"					"5"
			"wide"					"80"
			"tall"					"20"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"AllCaps"				"1"
			"border"				"Black"
		}
		
		"ClassBarBG7A"
		{
			"ControlName"			"ImagePanel"
			"fieldName"				"ClassBarBG7A"
			"xpos"					"c-199"
			"ypos"					"150"
			"zpos"					"2"
			"wide"					"159"
			"tall"					"20"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"tabPosition"			"0"
			"paintbackground"		"0"
			"paintborder"			"1"
			"border"				"Black"
		}
		"ClassBar7A"
		{
			"ControlName"			"ImagePanel"
			"fieldName"				"ClassBar7A"
			"xpos"					"c-195"
			"ypos"					"154"
			"zpos"					"3"
			"wide"					"151"
			"tall"					"12"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"tabPosition"			"0"	
			"fillcolor"				"Gray"
			"PaintBackgroundType"	"0"
			"alpha"					"50"
		}
		"ClassBarLabel7A"
		{
			"ControlName"			"Label"
			"fieldName"				"ClassBarLabel7A"
			"font"					"TF2Secondary16"
			"labelText"				"%classbarlabel7A%"
			"textAlignment"			"west"
			"xpos"					"c-195"
			"ypos"					"150"
			"zpos"					"6"
			"wide"					"100"
			"tall"					"20"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
		}
		
		"ClassBarBG7B"
		{
			"ControlName"			"ImagePanel"
			"fieldName"				"ClassBarBG7B"
			"xpos"					"c40"
			"ypos"					"150"
			"zpos"					"2"
			"wide"					"159"
			"tall"					"20"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"tabPosition"			"0"
			"paintbackground"		"0"
			"paintborder"			"1"
			"border"				"Black"
		}
		"ClassBar7B"
		{
			"ControlName"			"ImagePanel"
			"fieldName"				"ClassBar7B"
			"xpos"					"c44"
			"ypos"					"154"
			"zpos"					"3"
			"wide"					"151"
			"tall"					"12"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"tabPosition"			"0"	
			"fillcolor"				"Gray"
			"PaintBackgroundType"	"0"
			"alpha"					"50"
		}
		"ClassBarLabel7B"
		{
			"ControlName"			"Label"
			"fieldName"				"ClassBarLabel7B"
			"font"					"TF2Secondary16"
			"labelText"				"%classbarlabel7B%"
			"textAlignment"			"west"
			"xpos"					"c44"
			"ypos"					"150"
			"zpos"					"6"
			"wide"					"100"
			"tall"					"20"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
		}
		
		///////////////////////////////////////////////////
		///////////////////////BAR 8///////////////////////
		///////////////////////////////////////////////////
		
		"ClassLabel8"
		{
			"ControlName"			"Label"
			"fieldName"				"ClassLabel8"
			"font"					"TF2Secondary16"
			"labelText"				"%class8%"
			"textAlignment"			"center"
			"xpos"					"c-40"
			"ypos"					"170"
			"zpos"					"5"
			"wide"					"80"
			"tall"					"20"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"AllCaps"				"1"
			"border"				"Black"
		}
		
		"ClassBarBG8A"
		{
			"ControlName"			"ImagePanel"
			"fieldName"				"ClassBarBG8A"
			"xpos"					"c-199"
			"ypos"					"170"
			"zpos"					"2"
			"wide"					"159"
			"tall"					"20"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"tabPosition"			"0"
			"paintbackground"		"0"
			"paintborder"			"1"
			"border"				"Black"
		}
		"ClassBar8A"
		{
			"ControlName"			"ImagePanel"
			"fieldName"				"ClassBar8A"
			"xpos"					"c-195"
			"ypos"					"174"
			"zpos"					"3"
			"wide"					"151"
			"tall"					"12"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"tabPosition"			"0"	
			"fillcolor"				"Gray"
			"PaintBackgroundType"	"0"
			"alpha"					"50"
		}
		"ClassBarLabel8A"
		{
			"ControlName"			"Label"
			"fieldName"				"ClassBarLabel8A"
			"font"					"TF2Secondary16"
			"labelText"				"%classbarlabel8A%"
			"textAlignment"			"west"
			"xpos"					"c-195"
			"ypos"					"170"
			"zpos"					"6"
			"wide"					"100"
			"tall"					"20"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
		}
		
		"ClassBarBG8B"
		{
			"ControlName"			"ImagePanel"
			"fieldName"				"ClassBarBG8B"
			"xpos"					"c40"
			"ypos"					"170"
			"zpos"					"2"
			"wide"					"159"
			"tall"					"20"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"tabPosition"			"0"
			"paintbackground"		"0"
			"paintborder"			"1"
			"border"				"Black"
		}
		"ClassBar8B"
		{
			"ControlName"			"ImagePanel"
			"fieldName"				"ClassBar8B"
			"xpos"					"c44"
			"ypos"					"174"
			"zpos"					"3"
			"wide"					"151"
			"tall"					"12"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"tabPosition"			"0"	
			"fillcolor"				"Gray"
			"PaintBackgroundType"	"0"
			"alpha"					"50"
		}
		"ClassBarLabel8B"
		{
			"ControlName"			"Label"
			"fieldName"				"ClassBarLabel8B"
			"font"					"TF2Secondary16"
			"labelText"				"%classbarlabel8B%"
			"textAlignment"			"west"
			"xpos"					"c44"
			"ypos"					"170"
			"zpos"					"6"
			"wide"					"100"
			"tall"					"20"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
		}
		
		///////////////////////////////////////////////////
		///////////////////////BAR 9///////////////////////
		///////////////////////////////////////////////////
		
		"ClassLabel9"
		{
			"ControlName"			"Label"
			"fieldName"				"ClassLabel9"
			"font"					"TF2Secondary16"
			"labelText"				"%class9%"
			"textAlignment"			"center"
			"xpos"					"c-40"
			"ypos"					"190"
			"zpos"					"5"
			"wide"					"80"
			"tall"					"20"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"AllCaps"				"1"
			"border"				"Black"
		}
		
		"ClassBarBG9A"
		{
			"ControlName"			"ImagePanel"
			"fieldName"				"ClassBarBG9A"
			"xpos"					"c-199"
			"ypos"					"190"
			"zpos"					"2"
			"wide"					"159"
			"tall"					"20"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"tabPosition"			"0"
			"paintbackground"		"0"
			"paintborder"			"1"
			"border"				"Black"
		}
		"ClassBar9A"
		{
			"ControlName"			"ImagePanel"
			"fieldName"				"ClassBar9A"
			"xpos"					"c-195"
			"ypos"					"194"
			"zpos"					"3"
			"wide"					"151"
			"tall"					"12"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"tabPosition"			"0"	
			"fillcolor"				"Gray"
			"PaintBackgroundType"	"0"
			"alpha"					"50"
		}
		"ClassBarLabel9A"
		{
			"ControlName"			"Label"
			"fieldName"				"ClassBarLabel9A"
			"font"					"TF2Secondary16"
			"labelText"				"%classbarlabel9A%"
			"textAlignment"			"west"
			"xpos"					"c-195"
			"ypos"					"190"
			"zpos"					"6"
			"wide"					"100"
			"tall"					"20"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
		}
		
		"ClassBarBG9B"
		{
			"ControlName"			"ImagePanel"
			"fieldName"				"ClassBarBG9B"
			"xpos"					"c40"
			"ypos"					"190"
			"zpos"					"2"
			"wide"					"159"
			"tall"					"20"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"tabPosition"			"0"
			"paintbackground"		"0"
			"paintborder"			"1"
			"border"				"Black"
		}
		"ClassBar9B"
		{
			"ControlName"			"ImagePanel"
			"fieldName"				"ClassBar9B"
			"xpos"					"c44"
			"ypos"					"194"
			"zpos"					"3"
			"wide"					"151"
			"tall"					"12"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"tabPosition"			"0"	
			"fillcolor"				"Gray"
			"PaintBackgroundType"	"0"
			"alpha"					"50"
		}
		"ClassBarLabel9B"
		{
			"ControlName"			"Label"
			"fieldName"				"ClassBarLabel9B"
			"font"					"TF2Secondary16"
			"labelText"				"%classbarlabel9B%"
			"textAlignment"			"west"
			"xpos"					"c44"
			"ypos"					"190"
			"zpos"					"6"
			"wide"					"100"
			"tall"					"20"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
		}
		
		
		
		"TanLightBackgroundStats"
		{
			"ControlName"			"EditablePanel"
			"fieldName"				"TanLightBackgroundStats"
			"xpos"					"c-205"
			"ypos"					"215"
			"zpos"					"0"
			"wide"					"410"
			"tall"					"87"
			"visible"				"1"
			"enabled"				"1"
			"border"				"BlackTransparent30"
		}
		
		"Separator"
		{
			"ControlName"			"EditablePanel"
			"fieldName"				"Separator"
			"xpos"					"c0"
			"ypos"					"220"
			"zpos"					"0"
			"wide"					"1"
			"tall"					"77"
			"visible"				"1"
			"enabled"				"1"
			"bgcolor_override"		"TanLightTransparent"
		}
		
		"RecordsBG"
		{
			"ControlName"			"EditablePanel"
			"fieldName"				"RecordsBG"
			"xpos"					"9999"
		}
		"RecordsLabel1"
		{
			"ControlName"			"Label"
			"fieldName"				"RecordsLabel1"
			"xpos"					"9999"
		}
		"RecordsSubBG1"
		{
			"ControlName"			"ImagePanel"
			"fieldName"				"RecordsSubBG1"
			"xpos"					"9999"
		}
		"RecordsLabel"
		{
			"ControlName"			"Label"
			"fieldName"				"RecordsLabel"
			"xpos"					"9999"
		}
		
		"OverallRecord1Label"
		{
			"ControlName"			"Label"
			"fieldName"				"OverallRecord1Label"
			"font"					"TF2Secondary12"
			"labelText"				"%classrecord1label%"
			"textAlignment"			"west"
			"xpos"					"c-200"
			"ypos"					"219"
			"zpos"					"8"
			"wide"					"90"
			"tall"					"10"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"AllCaps"				"1"
			"fgcolor_override"		"TanLight"
		}
		
		"OverallRecord1Value"
		{
			"ControlName"			"Label"
			"fieldName"				"OverallRecord1Value"
			"font"					"TF2Secondary12"
			"labelText"				"%classrecord1value%"
			"textAlignment"			"east"
			"xpos"					"c-94"
			"ypos"					"219"
			"zpos"					"5"
			"wide"					"90"
			"tall"					"10"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"AllCaps"				"1"
			"fgcolor_override"		"TanLight"
		}
		
		"OverallRecord2Label"
		{
			"ControlName"			"Label"
			"fieldName"				"OverallRecord2Label"
			"font"					"TF2Secondary12"
			"labelText"				"%classrecord2label%"
			"textAlignment"			"west"
			"xpos"					"c-200"
			"ypos"					"229"
			"zpos"					"8"
			"wide"					"90"
			"tall"					"10"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"AllCaps"				"1"
			"fgcolor_override"		"TanLight"
		}
		
		"OverallRecord2Value"
		{
			"ControlName"			"Label"
			"fieldName"				"OverallRecord2Value"
			"font"					"TF2Secondary12"
			"labelText"				"%classrecord2value%"
			"textAlignment"			"east"
			"xpos"					"c-94"
			"ypos"					"229"
			"zpos"					"5"
			"wide"					"90"
			"tall"					"10"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"AllCaps"				"1"
			"fgcolor_override"		"TanLight"
		}
		
		"OverallRecord3Label"
		{
			"ControlName"			"Label"
			"fieldName"				"OverallRecord3Label"
			"font"					"TF2Secondary12"
			"labelText"				"%classrecord3label%"
			"textAlignment"			"west"
			"xpos"					"c-200"
			"ypos"					"239"
			"zpos"					"8"
			"wide"					"90"
			"tall"					"10"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"AllCaps"				"1"
			"fgcolor_override"		"TanLight"
		}
		
		"OverallRecord3Value"
		{
			"ControlName"			"Label"
			"fieldName"				"OverallRecord3Value"
			"font"					"TF2Secondary12"
			"labelText"				"%classrecord3value%"
			"textAlignment"			"east"
			"xpos"					"c-94"
			"ypos"					"239"
			"zpos"					"5"
			"wide"					"90"
			"tall"					"10"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"AllCaps"				"1"
			"fgcolor_override"		"TanLight"
		}
		
		"OverallRecord4Label"
		{
			"ControlName"			"Label"
			"fieldName"				"OverallRecord4Label"
			"font"					"TF2Secondary12"
			"labelText"				"%classrecord4label%"
			"textAlignment"			"west"
			"xpos"					"c-200"
			"ypos"					"249"
			"zpos"					"8"
			"wide"					"90"
			"tall"					"10"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"AllCaps"				"1"
			"fgcolor_override"		"TanLight"
		}
		
		"OverallRecord4Value"
		{
			"ControlName"			"Label"
			"fieldName"				"OverallRecord4Value"
			"font"					"TF2Secondary12"
			"labelText"				"%classrecord4value%"
			"textAlignment"			"east"
			"xpos"					"c-94"
			"ypos"					"249"
			"zpos"					"5"
			"wide"					"90"
			"tall"					"10"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"AllCaps"				"1"
			"fgcolor_override"		"TanLight"
		}
		
		"OverallRecord5Label"
		{
			"ControlName"			"Label"
			"fieldName"				"OverallRecord5Label"
			"font"					"TF2Secondary12"
			"labelText"				"%classrecord5label%"
			"textAlignment"			"west"
			"xpos"					"c-200"
			"ypos"					"259"
			"zpos"					"8"
			"wide"					"90"
			"tall"					"10"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"AllCaps"				"1"
			"fgcolor_override"		"TanLight"
		}
		
		"OverallRecord5Value"
		{
			"ControlName"			"Label"
			"fieldName"				"OverallRecord5Value"
			"font"					"TF2Secondary12"
			"labelText"				"%classrecord5value%"
			"textAlignment"			"east"
			"xpos"					"c-94"
			"ypos"					"259"
			"zpos"					"5"
			"wide"					"90"
			"tall"					"10"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"AllCaps"				"1"
			"fgcolor_override"		"TanLight"
		}
		
		"OverallRecord6Label"
		{
			"ControlName"			"Label"
			"fieldName"				"OverallRecord6Label"
			"font"					"TF2Secondary12"
			"labelText"				"%classrecord6label%"
			"textAlignment"			"west"
			"xpos"					"c-200"
			"ypos"					"269"
			"zpos"					"8"
			"wide"					"90"
			"tall"					"10"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"AllCaps"				"1"
			"fgcolor_override"		"TanLight"
		}
		
		"OverallRecord6Value"
		{
			"ControlName"			"Label"
			"fieldName"				"OverallRecord6Value"
			"font"					"TF2Secondary12"
			"labelText"				"%classrecord6value%"
			"textAlignment"			"east"
			"xpos"					"c-94"
			"ypos"					"269"
			"zpos"					"5"
			"wide"					"90"
			"tall"					"10"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"AllCaps"				"1"
			"fgcolor_override"		"TanLight"
		}
		
		"OverallRecord7Label"
		{
			"ControlName"			"Label"
			"fieldName"				"OverallRecord7Label"
			"font"					"TF2Secondary12"
			"labelText"				"%classrecord7label%"
			"textAlignment"			"west"
			"xpos"					"c-200"
			"ypos"					"279"
			"zpos"					"8"
			"wide"					"90"
			"tall"					"10"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"AllCaps"				"1"
			"fgcolor_override"		"TanLight"
		}
		
		"OverallRecord7Value"
		{
			"ControlName"			"Label"
			"fieldName"				"OverallRecord7Value"
			"font"					"TF2Secondary12"
			"labelText"				"%classrecord7value%"
			"textAlignment"			"east"
			"xpos"					"c-94"
			"ypos"					"279"
			"zpos"					"5"
			"wide"					"90"
			"tall"					"10"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"AllCaps"				"1"
			"fgcolor_override"		"TanLight"
		}
		
		"OverallRecord8Label"
		{
			"ControlName"			"Label"
			"fieldName"				"OverallRecord8Label"
			"font"					"TF2Secondary12"
			"labelText"				"%classrecord8label%"
			"textAlignment"			"west"
			"xpos"					"c-200"
			"ypos"					"289"
			"zpos"					"8"
			"wide"					"90"
			"tall"					"10"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"AllCaps"				"1"
			"fgcolor_override"		"TanLight"
		}
		
		"OverallRecord8Value"
		{
			"ControlName"			"Label"
			"fieldName"				"OverallRecord8Value"
			"font"					"TF2Secondary12"
			"labelText"				"%classrecord8value%"
			"textAlignment"			"east"
			"xpos"					"c-94"
			"ypos"					"289"
			"zpos"					"5"
			"wide"					"90"
			"tall"					"10"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"AllCaps"				"1"
			"fgcolor_override"		"TanLight"
		}
		
		"OverallRecord9Label"
		{
			"ControlName"			"Label"
			"fieldName"				"OverallRecord9Label"
			"font"					"TF2Secondary12"
			"labelText"				"%classrecord9label%"
			"textAlignment"			"west"
			"xpos"					"c5"
			"ypos"					"219"
			"zpos"					"8"
			"wide"					"90"
			"tall"					"10"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"AllCaps"				"1"
			"fgcolor_override"		"TanLight"
		}
		
		"OverallRecord9Value"
		{
			"ControlName"			"Label"
			"fieldName"				"OverallRecord9Value"
			"font"					"TF2Secondary12"
			"labelText"				"%classrecord9value%"
			"textAlignment"			"east"
			"xpos"					"c110"
			"ypos"					"219"
			"zpos"					"5"
			"wide"					"90"
			"tall"					"10"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"AllCaps"				"1"
			"fgcolor_override"		"TanLight"
		}
		
		"OverallRecord10Label"
		{
			"ControlName"			"Label"
			"fieldName"				"OverallRecord10Label"
			"font"					"TF2Secondary12"
			"labelText"				"%classrecord10label%"
			"textAlignment"			"west"
			"xpos"					"c5"
			"ypos"					"229"
			"zpos"					"8"
			"wide"					"90"
			"tall"					"10"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"AllCaps"				"1"
			"fgcolor_override"		"TanLight"
		}
		
		"OverallRecord10Value"
		{
			"ControlName"			"Label"
			"fieldName"				"OverallRecord10Value"
			"font"					"TF2Secondary12"
			"labelText"				"%classrecord10value%"
			"textAlignment"			"east"
			"xpos"					"c110"
			"ypos"					"229"
			"zpos"					"5"
			"wide"					"90"
			"tall"					"10"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"AllCaps"				"1"
			"fgcolor_override"		"TanLight"
		}
		
		"OverallRecord11Label"
		{
			"ControlName"			"Label"
			"fieldName"				"OverallRecord11Label"
			"font"					"TF2Secondary12"
			"labelText"				"%classrecord11label%"
			"textAlignment"			"west"
			"xpos"					"c5"
			"ypos"					"239"
			"zpos"					"8"
			"wide"					"90"
			"tall"					"10"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"AllCaps"				"1"
			"fgcolor_override"		"TanLight"
		}
		
		"OverallRecord11Value"
		{
			"ControlName"			"Label"
			"fieldName"				"OverallRecord11Value"
			"font"					"TF2Secondary12"
			"labelText"				"%classrecord11value%"
			"textAlignment"			"east"
			"xpos"					"c110"
			"ypos"					"239"
			"zpos"					"5"
			"wide"					"90"
			"tall"					"10"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"AllCaps"				"1"
			"fgcolor_override"		"TanLight"
		}
		
		"OverallRecord12Label"
		{
			"ControlName"			"Label"
			"fieldName"				"OverallRecord12Label"
			"font"					"TF2Secondary12"
			"labelText"				"%classrecord12label%"
			"textAlignment"			"west"
			"xpos"					"c5"
			"ypos"					"249"
			"zpos"					"8"
			"wide"					"90"
			"tall"					"10"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"AllCaps"				"1"
			"fgcolor_override"		"TanLight"
		}
		
		"OverallRecord12Value"
		{
			"ControlName"			"Label"
			"fieldName"				"OverallRecord12Value"
			"font"					"TF2Secondary12"
			"labelText"				"%classrecord12value%"
			"textAlignment"			"east"
			"xpos"					"c110"
			"ypos"					"249"
			"zpos"					"5"
			"wide"					"90"
			"tall"					"10"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"AllCaps"				"1"
			"fgcolor_override"		"TanLight"
		}
		
		"OverallRecord13Label"
		{
			"ControlName"			"Label"
			"fieldName"				"OverallRecord13Label"
			"font"					"TF2Secondary12"
			"labelText"				"%classrecord13label%"
			"textAlignment"			"west"
			"xpos"					"c5"
			"ypos"					"259"
			"zpos"					"8"
			"wide"					"90"
			"tall"					"10"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"AllCaps"				"1"
			"fgcolor_override"		"TanLight"
		}
		
		"OverallRecord13Value"
		{
			"ControlName"			"Label"
			"fieldName"				"OverallRecord13Value"
			"font"					"TF2Secondary12"
			"labelText"				"%classrecord13value%"
			"textAlignment"			"east"
			"xpos"					"c110"
			"ypos"					"259"
			"zpos"					"5"
			"wide"					"90"
			"tall"					"10"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"AllCaps"				"1"
			"fgcolor_override"		"TanLight"
		}
		
		"OverallRecord14Label"
		{
			"ControlName"			"Label"
			"fieldName"				"OverallRecord14Label"
			"font"					"TF2Secondary12"
			"labelText"				"%classrecord14label%"
			"textAlignment"			"west"
			"xpos"					"c5"
			"ypos"					"269"
			"zpos"					"8"
			"wide"					"90"
			"tall"					"10"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"AllCaps"				"1"
			"fgcolor_override"		"TanLight"
		}
		
		"OverallRecord14Value"
		{
			"ControlName"			"Label"
			"fieldName"				"OverallRecord14Value"
			"font"					"TF2Secondary12"
			"labelText"				"%classrecord14value%"
			"textAlignment"			"east"
			"xpos"					"c110"
			"ypos"					"269"
			"zpos"					"5"
			"wide"					"90"
			"tall"					"10"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"AllCaps"				"1"
			"fgcolor_override"		"TanLight"
		}
		
		"OverallRecord15Label"
		{
			"ControlName"			"Label"
			"fieldName"				"OverallRecord15Label"
			"font"					"TF2Secondary12"
			"labelText"				"%classrecord15label%"
			"textAlignment"			"west"
			"xpos"					"c5"
			"ypos"					"279"
			"zpos"					"8"
			"wide"					"90"
			"tall"					"10"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"AllCaps"				"1"
			"fgcolor_override"		"TanLight"
		}
		
		"OverallRecord15Value"
		{
			"ControlName"			"Label"
			"fieldName"				"OverallRecord15Value"
			"font"					"TF2Secondary12"
			"labelText"				"%classrecord15value%"
			"textAlignment"			"east"
			"xpos"					"c110"
			"ypos"					"279"
			"zpos"					"5"
			"wide"					"90"
			"tall"					"10"
			"autoResize"			"0"
			"pinCorner"				"0"
			"visible"				"1"
			"enabled"				"1"
			"AllCaps"				"1"
			"fgcolor_override"		"TanLight"
		}
	}
	
	"ResetStatsButton"
	{
		"ControlName"				"CExButton"
		"fieldName"					"ResetStatsButton"
		"xpos"						"9999"
		"wide"						"0"
		"tall"						"0"
		"visible"					"0"
		"enabled"					"0"
	}
	"ResetStatsButton2"
	{
		"ControlName"				"CExButton"
		"fieldName"					"ResetStatsButton2"
		"xpos"						"r20"
		"ypos"						"0"
		"zpos"						"20"
		"wide"						"18"
		"tall"						"18"
		"autoResize"				"0"
		"pinCorner"					"0"
		"visible"					"1"
		"enabled"					"1"
		"tabPosition"				"0"
		"labelText"					"D"
		"font"						"icon12"
		"textAlignment"				"center"
		"dulltext"					"0"
		"brighttext"				"0"
		"Command"					"resetstatsbutton"
		
		"sound_depressed"			"UI/buttonclick.wav"
		"sound_released"			"UI/buttonclickrelease.wav"
		
		"paintbackground" 			"0"
		
		"border_default"			"Black"
		"border_armed"				"Select"
	}
	
	
	"CloseButton"
	{
		"ControlName"				"Button"
		"fieldName"					"CloseButton"
		"xpos"						"9999"
	}
	"TipImage"
	{
		"ControlName"				"CTFImagePanel"
		"fieldName"					"TipImage"
		"xpos"						"9999"
	}
	"TipText"
	{
		"ControlName"				"Label"
		"fieldName"					"TipText"
		"xpos"						"9999"
	}
	"NextTipButton"
	{
		"ControlName"				"Button"
		"fieldName"					"NextTipButton"
		"xpos"						"9999"
	}
	"MainBackground"
	{
		"ControlName"				"ImagePanel"
		"fieldName"					"MainBackground"
		"xpos"						"9999"
	}
	"OnYourWayLabel"
	{
		"ControlName"				"CExLabel"
		"fieldName"					"OnYourWayLabel"
		"xpos"						"9999"
	}					
	"MapLabel"
	{
		"ControlName"				"CExLabel"
		"fieldName"					"MapLabel"
		"xpos"						"9999"
	}
	"MapType"
	{
		"ControlName"				"CExLabel"
		"fieldName"					"MapType"
		"xpos"						"9999"
	}
}